apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkwarden
  template:
    metadata:
      labels:
        app: linkwarden
    spec:
      containers:
        - name: linkwarden
          image: redrathnure/linkwarden:2.15
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: linkwarden-storage
              mountPath: /var/lib/postgresql/data
#        - name: postgres
#          image: postgres:15.19
#          ports:
#            - containerPort: 5432
#          env:
#            - name: POSTGRES_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: postgres-secret
#                  key: password
#          volumeMounts:
#            - name: linkwarden-storage
#              mountPath: /var/lib/postgresql/data
